version: '3.8'

services:
  nginx:
    container_name: maxmoll_nginx
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./_docker/nginx/log:/var/log/nginx
    working_dir: /var/www
    restart: unless-stopped
    networks:
      - maxmoll_network
  app:
    container_name: maxmoll_app
    build:
      context: ./_docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - maxmoll_network

networks:
  maxmoll_network:
    driver: bridge